apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Network policies will be deployed to the default namespace
# but can be overlayed for other namespaces as needed
namespace: default

resources:
  - default-deny.yaml
  - allow-dns.yaml
  - allow-internet.yaml
