apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - require-resource-limits.yaml
  - disallow-privileged.yaml
  - require-labels.yaml

commonLabels:
  app: kyverno-policy

