apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: falco

resources:
  - namespace.yaml
  - deployment.yaml
  # Falco is typically installed via Helm chart
  # For production, use:
  # helm install falco falcosecurity/falco --namespace falco

commonLabels:
  app: falco
