apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: homelab-security
  namespace: argocd
spec:
  project: base-infrastructure
  source:
    repoURL: https://github.com/devsaumya/homelab-infrastructure
    targetRevision: master
    path: k8s/security
  destination:
    server: https://kubernetes.default.svc
    namespace: security
  syncPolicy:
    automated: null
