apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:
  - falco/application.yaml
  - kyverno-crds-app.yaml
  - kyverno/application.yaml
  - sealed-secrets/application.yaml
