apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: staging

resources:
  - ../../base/namespaces
  - ../../base/adguard
  - ../../base/traefik
  - ../../base/cert-manager
  - ../../base/network-policies

commonLabels:
  environment: staging

patchesStrategicMerge:
  - |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: adguard-home
      namespace: dns-system
    spec:
      replicas: 1  # Single replica for staging

