apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - kyverno-crds.yaml

# Add sync-wave annotation to deploy CRDs before controllers
commonAnnotations:
  argocd.argoproj.io/sync-wave: "-1"
