apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kyverno
  namespace: argocd
spec:
  project: security

  destination:
    server: https://kubernetes.default.svc
    namespace: kyverno

  source:
    repoURL: https://kyverno.github.io/kyverno/
    chart: kyverno
    targetRevision: 3.2.6
    helm:
      values: |
        installCRDs: false

        backgroundController:
          enabled: true

        reportsController:
          enabled: true

        cleanupController:
          enabled: false

        cleanupJobs:
          admissionReports:
            enabled: false
          clusterAdmissionReports:
            enabled: false
          ephemeralReports:
            enabled: false
          clusterEphemeralReports:
            enabled: false

  syncPolicy:
    automated:
      prune: false
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true

  ignoreDifferences:
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
      name: clusterpolicies.kyverno.io
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
      name: policies.kyverno.io