apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kyverno
  namespace: argocd
spec:
  project: security

  destination:
    server: https://kubernetes.default.svc
    namespace: kyverno

  source:
    repoURL: https://kyverno.github.io/kyverno/
    chart: kyverno
    targetRevision: 3.2.6
    helm:
      values: |
        cleanupController:
          enabled: false
        reportsController:
          enabled: true
        admissionController:
          enabled: true
        backgroundController:
          enabled: true

  syncPolicy:
    automated:
      prune: false
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
      - SkipHooks=true

  ignoreDifferences:
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
      name: clusterpolicies.kyverno.io
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
      name: policies.kyverno.io
    - group: batch
      kind: Job
      namespace: kyverno