apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kyverno

resources:
  - namespace.yaml
  - deployment.yaml
  # Kyverno is typically installed via Helm chart
  # For production, use:
  # helm install kyverno kyverno/kyverno --namespace kyverno

commonLabels:
  app: kyverno
