---
# roles/common/handlers/main.yml

- name: restart cron
  service:
    name: cron
    state: restarted
  when:
    - ansible_os_family == "Debian"
    - "'cron' in ansible_facts.services"
  ignore_errors: yes
