apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: production

resources:
  - ../../base/namespaces
  - ../../base/adguard
  - ../../base/traefik
  - ../../base/cert-manager
  - ../../base/cloudflare-tunnel
  - ../../base/network-policies

commonLabels:
  environment: production

patchesStrategicMerge:
  - |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: adguard-home
      namespace: dns-system
    spec:
      replicas: 2  # HA in production

