apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dns-system

resources:
  - deployment.yaml
  - service.yaml
  - pvc-config.yaml
  - pvc-work.yaml
  - pvc-data.yaml

commonLabels:
  app: adguard-home
